### ISSUE TITLE
RPC connection calls fail after update to Bitcoin Core 28.0

### ISSUE THREAD

**Issue by Funman2** [getumbrel/umbrel-apps#1727] opened 2024-11-01 08:46 UTC
All RPC Connections seem to fail after the recent Update to Bitcoin Core 28.0.
Specter can not connect from local LAN, as well as sparrow.

How could i resolve this? Reinstalling Bitcoin core would screw all my blockchain data and the lightning wallet, right?

Also the internal specter App on Umbrel fails to connect.

![Bildschirmfoto vom 2024-11-01 08-51-24](https://github.com/user-attachments/assets/292cc64a-2854-498c-a30a-288d9eea60ef)
![Bildschirmfoto vom 2024-11-01 08-38-27](https://github.com/user-attachments/assets/99bacaae-a26f-4305-a23e-f267db8325ee)

**Comment by Funman2** [comment] 2024-11-01 10:03
also found these error messages a lot in bitcoin app protocols, although I tried in Advanced Properties to increase RPC call limit up to 1000:
bitcoin_bitcoind_1 | 2024-11-01T05:32:10Z New block-relay-only v2 peer connected: version: 70016, blocks=868360, peer=160
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
bitcoin_bitcoind_1 | 2024-11-01T05:35:58Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting

**Comment by nmfretz** [comment] 2024-11-04 05:24
Hey @Funman2, just closing this as a duplicate of  https://github.com/getumbrel/umbrel-apps/issues/1712

For others making their way here, Specter devs have been notified and are hopefully working on a fix: https://github.com/cryptoadvance/specter-desktop/issues/2473

The Sparrow behaviour is expected and explained here: https://github.com/getumbrel/umbrel-apps/issues/1712#issuecomment-2453825775

**Closed by nmfretz** 2024-11-04 05:24 UTC
